CREATE TYPE [DataSync].[SWIFT_ERP_SKU_dss_BulkType_2e0cdad2-f0d7-461c-b2b2-37ffb6d7edf4] AS TABLE (
    [SKU]                        INT             NULL,
    [CODE_SKU]                   VARCHAR (50)    NOT NULL,
    [DESCRIPTION_SKU]            VARCHAR (MAX)   NULL,
    [BARCODE_SKU]                VARCHAR (30)    NULL,
    [NAME_PROVIDER]              VARCHAR (100)   NULL,
    [COST]                       FLOAT (53)      NULL,
    [LIST_PRICE]                 NUMERIC (18)    NULL,
    [MEASURE]                    VARCHAR (50)    NULL,
    [NAME_CLASSIFICATION]        VARCHAR (150)   NULL,
    [VALUE_TEXT_CLASSIFICATION]  VARCHAR (32)    NULL,
    [HANDLE_SERIAL_NUMBER]       VARCHAR (2)     NULL,
    [HANDLE_BATCH]               VARCHAR (2)     NULL,
    [FROM_ERP]                   VARCHAR (2)     NULL,
    [PRICE]                      NUMERIC (19, 6) NULL,
    [LIST_NUM]                   SMALLINT        NOT NULL,
    [CODE_PROVIDER]              VARCHAR (30)    NULL,
    [LAST_UPDATE]                DATETIME        NULL,
    [LAST_UPDATE_BY]             VARCHAR (50)    NULL,
    [UNIT_MEASURE_SKU]           INT             NULL,
    [WEIGHT_SKU]                 NUMERIC (18, 2) NULL,
    [VOLUME_SKU]                 NUMERIC (18, 2) NULL,
    [LONG_SKU]                   NUMERIC (18, 2) NULL,
    [WIDTH_SKU]                  NUMERIC (18, 2) NULL,
    [HIGH_SKU]                   NUMERIC (18, 2) NULL,
    [sync_update_peer_timestamp] BIGINT          NULL,
    [sync_update_peer_key]       INT             NULL,
    [sync_create_peer_timestamp] BIGINT          NULL,
    [sync_create_peer_key]       INT             NULL,
    PRIMARY KEY CLUSTERED ([CODE_SKU] ASC, [LIST_NUM] ASC));

