CREATE TYPE [DataSync].[SWIFT_ERP_CUSTOMERS_dss_BulkType_2e0cdad2-f0d7-461c-b2b2-37ffb6d7edf4] AS TABLE (
    [CUSTOMER]                   NVARCHAR (15)   NULL,
    [CODE_CUSTOMER]              NVARCHAR (15)   NOT NULL,
    [NAME_CUSTOMER]              NVARCHAR (100)  NULL,
    [PHONE_CUSTOMER]             NVARCHAR (20)   NULL,
    [ADRESS_CUSTOMER]            NVARCHAR (100)  NULL,
    [CLASSIFICATION_CUSTOMER]    VARCHAR (1)     NULL,
    [CONTACT_CUSTOMER]           NVARCHAR (90)   NULL,
    [CODE_ROUTE]                 VARCHAR (30)    NULL,
    [LAST_UPDATE]                DATETIME        NULL,
    [LAST_UPDATE_BY]             VARCHAR (30)    NULL,
    [SELLER_DEFAULT_CODE]        NVARCHAR (155)  NULL,
    [CREDIT_LIMIT]               NUMERIC (19, 6) NULL,
    [FROM_ERP]                   INT             NULL,
    [NAME_ROUTE]                 VARCHAR (30)    NULL,
    [NAME_CLASSIFICATION]        VARCHAR (30)    NULL,
    [GPS]                        VARCHAR (100)   NULL,
    [LATITUDE]                   VARCHAR (50)    NULL,
    [LONGITUDE]                  VARCHAR (50)    NULL,
    [FREQUENCY]                  NVARCHAR (100)  NULL,
    [SUNDAY]                     CHAR (1)        NULL,
    [MONDAY]                     CHAR (1)        NULL,
    [TUESDAY]                    CHAR (1)        NULL,
    [WEDNESDAY]                  CHAR (1)        NULL,
    [THURSDAY]                   CHAR (1)        NULL,
    [FRIDAY]                     CHAR (1)        NULL,
    [SATURDAY]                   CHAR (1)        NULL,
    [SCOUTING_ROUTE]             NVARCHAR (100)  NULL,
    [sync_update_peer_timestamp] BIGINT          NULL,
    [sync_update_peer_key]       INT             NULL,
    [sync_create_peer_timestamp] BIGINT          NULL,
    [sync_create_peer_key]       INT             NULL,
    PRIMARY KEY CLUSTERED ([CODE_CUSTOMER] ASC));

