
-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	29-02-2016
-- Description:			SP que importa ordenes de compra

/*
-- Ejemplo de Ejecucion:
				-- 
				EXEC [ferco].[BULK_DATA_SP_IMPORT_PURCHASE_ORDER]
*/
-- =============================================
CREATE PROCEDURE ferco.BULK_DATA_SP_IMPORT_PURCHASE_ORDER
AS
BEGIN
  SET NOCOUNT ON;
  --
  PRINT 'INSERTA EN PICKING'
  DELETE FROM [ferco].[SWIFT_ERP_PICKING]
  INSERT INTO [ferco].[SWIFT_ERP_PICKING]
    SELECT
      *
    FROM [SWIFT_INTERFACES_ONLINE].[ferco].[ERP_VIEW_PICKING]
  --
  PRINT 'INSERTA EN PURCHASE_ORDER_DETAIL'
  DELETE FROM [ferco].[SWIFT_ERP_PURCHASE_ORDER_DETAIL]
  INSERT INTO [ferco].[SWIFT_ERP_PURCHASE_ORDER_DETAIL]
    SELECT
      *
    FROM [SWIFT_INTERFACES_ONLINE].[ferco].[ERP_VIEW_PURCHASE_ORDER_DETAIL]
  --
  PRINT 'INSERTA EN PURCHASE_ORDER_HEADER'
  DELETE FROM [ferco].[SWIFT_ERP_PURCHASE_ORDER_HEADER]
  INSERT INTO [ferco].[SWIFT_ERP_PURCHASE_ORDER_HEADER]
    SELECT
      *
    FROM [SWIFT_INTERFACES_ONLINE].[ferco].[ERP_VIEW_PURCHASE_ORDER_HEADER]
  --
  PRINT 'INSERTA EN PURCHASE_SERIE_DETAIL'
  DELETE FROM [ferco].[SWIFT_ERP_PURCHASE_SERIE_DETAIL]
  INSERT INTO [ferco].[SWIFT_ERP_PURCHASE_SERIE_DETAIL]
    SELECT
      *
    FROM [SWIFT_INTERFACES_ONLINE].[ferco].[ERP_VIEW_PURCHASE_SERIE_DETAIL]
END
