
CREATE PROCEDURE FERCO.OP_WMS_SP_GET_ACUERDOS_X_CLIENTE @pResult VARCHAR(250) OUTPUT
AS
BEGIN
  SET NOCOUNT ON;
  BEGIN TRAN
  BEGIN
    SELECT
      *
    FROM FERCO.OP_WMS_ACUERDOS_X_CLIENTE
    INNER JOIN FERCO.OP_WMS_TARIFICADOR_HEADER
      ON ACUERDO_COMERCIAL_ID = ACUERDO_COMERCIAL
    INNER JOIN FERCO.OP_WMS_VIEW_CLIENTS
      ON CLIENT_ID = CLIENT_CODE COLLATE DATABASE_DEFAULT

  END
  IF @@error = 0
  BEGIN
    SELECT
      @pResult = 'OK'
    COMMIT TRAN
  END
  ELSE
  BEGIN
    ROLLBACK TRAN
    SELECT
      @pResult = ERROR_MESSAGE()
  END

END
