
-- =============================================
-- Autor:				rudi.garcia
-- Fecha de Creacion: 	18-ene-17 @ TeamErgon Sprint 1
-- Description:			obtiene el detalle de una orde de compra en sap de la cual se hizo una recepcion 

-- Modificado Fecha
-- anonymous
-- ningun motivo

-- Modificacion 9/17/2017 @ Reborn-Team Sprint Collin
-- diego.as
-- Se agregan columnas @WAREHOUSE_CODE_PARAMETER AS WarehouseCode
-- TONE y CALIBER

/*
-- Ejemplo de Ejecucion:
         EXEC [FERCO].[OP_WMS_SP_GET_RECEPTION_DETAILS] @RECEPTION_HEADER = 1208
		 EXEC [FERCO].[OP_WMS_SP_GET_RECEPTION_DETAILS1] @RECEPTION_HEADER = 1208
*/
CREATE PROCEDURE FERCO.OP_WMS_SP_GET_RECEPTION_DETAILS1 (@RECEPTION_HEADER INT)
AS
BEGIN
  --
  SET NOCOUNT ON;
  --
  DECLARE @WAREHOUSE_CODE_PARAMETER VARCHAR(15) = NULL;
  --
  SELECT
    @WAREHOUSE_CODE_PARAMETER = [C].[TEXT_VALUE]
  FROM [FERCO].[OP_WMS_CONFIGURATIONS] AS [C]
  WHERE [C].[PARAM_NAME] = 'ERP_WAREHOUSE_PURCHASE_ORDER';
  --

  SELECT
    [D].[ERP_RECEPTION_DOCUMENT_HEADER_ID] [DocEntry]
   ,[FERCO].[OP_WMS_GET_STRING_FROM_CHAR]([TR].[MATERIAL_CODE], '/') [ItemCode]
   ,SUM([TR].[QUANTITY_UNITS]) [Quantity]
   ,[D].[LINE_NUM] [LineNum]
   ,CAST([D].[ERP_OBJECT_TYPE] AS VARCHAR) [ObjType]
   ,[H].[DOC_ID] [DocEntryErp]
   ,@WAREHOUSE_CODE_PARAMETER AS WarehouseCode
  FROM [FERCO].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL] [D]
  INNER JOIN [FERCO].[OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER] [H]
    ON [D].[ERP_RECEPTION_DOCUMENT_HEADER_ID] = [H].[ERP_RECEPTION_DOCUMENT_HEADER_ID]
  INNER JOIN [FERCO].[OP_WMS_TASK_LIST] [T]
    ON [H].[TASK_ID] = [T].[SERIAL_NUMBER]
  INNER JOIN [FERCO].[OP_WMS_TRANS] TR ON [TR].[MATERIAL_CODE] = [D].[MATERIAL_ID]
  AND [TR].[TASK_ID] = [H].[TASK_ID] AND [TR].[TRANS_TYPE] = 'INGRESO_GENERAL' AND [TR].[STATUS] = 'PROCESSED'
  WHERE [D].[ERP_RECEPTION_DOCUMENT_HEADER_ID] = @RECEPTION_HEADER
  GROUP BY [D].[ERP_RECEPTION_DOCUMENT_HEADER_ID]
          ,[H].[DOC_ID]
          ,[TR].[MATERIAL_CODE]
          ,[D].[LINE_NUM]
          ,[D].[ERP_OBJECT_TYPE]
  UNION
  SELECT
    -1 [DocEntry]
   ,[FERCO].[OP_WMS_GET_STRING_FROM_CHAR]([TR].[MATERIAL_CODE], '/') [ItemCode]
   ,SUM([TR].[QUANTITY_UNITS]) [Quantity]
   ,-1 [LineNum]
   ,'22' [ObjType]
   ,-1 [DocEntryErp]
   ,@WAREHOUSE_CODE_PARAMETER AS WarehouseCode
  FROM [FERCO].[OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER] [H]
  INNER JOIN [FERCO].[OP_WMS_TASK_LIST] [T]
    ON [H].[TASK_ID] = [T].[SERIAL_NUMBER]
   INNER JOIN [FERCO].[OP_WMS_TRANS] TR ON 
   [TR].[TASK_ID] = [H].[TASK_ID] AND [TR].[TRANS_TYPE] = 'INGRESO_GENERAL' AND [TR].[STATUS] = 'PROCESSED'
  LEFT JOIN [FERCO].[OP_WMS_ERP_RECEPTION_DOCUMENT_DETAIL] [D]
    ON [D].[ERP_RECEPTION_DOCUMENT_HEADER_ID] = [H].[ERP_RECEPTION_DOCUMENT_HEADER_ID]
      AND [TR].[MATERIAL_CODE] = [D].[MATERIAL_ID]
  WHERE [H].[ERP_RECEPTION_DOCUMENT_HEADER_ID] = @RECEPTION_HEADER
  AND [D].[ERP_RECEPTION_DOCUMENT_DETAIL_ID] IS NULL
  GROUP BY [TR].[MATERIAL_CODE];


END;

