-- =============================================


/*
-- Ejemplo de Ejecucion:
				EXEC [FERCO].[FERCO.PICKING_EFFICIENCY]						
					
   */
-- =============================================
CREATE PROCEDURE FERCO.PICKING_EFFICIENCY
AS
BEGIN
	
SELECT [WAVE_PICKING_ID], 
			MAX ([COMPLETED_DATE]) [COMPLETED_DATE] 
			INTO #COMPLETED_TASK 
			FROM [FERCO].[OP_WMS_TASK_LIST]     
			WHERE CAST([ASSIGNED_DATE] AS DATE) BETWEEN CAST(getdate()-30 AS DATE) AND CAST(getdate()  AS DATE) 
			GROUP BY [WAVE_PICKING_ID] HAVING MIN( [IS_COMPLETED] ) > 0       
		
	SELECT [T].[WAVE_PICKING_ID],
			[T].[MATERIAL_ID],
			SUM([T].[QUANTITY_ASSIGNED]) [QUANTITY_ASSIGNED],
			MAX([T].[ASSIGNED_DATE]) [ASSIGNED_DATE],
			MAX([T].[ACCEPTED_DATE]) [ACCEPTED_DATE],
			MAX([T].[COMPLETED_DATE]) [COMPLETED_DATE],
			RANK() OVER (PARTITION BY [T].[WAVE_PICKING_ID] ORDER BY MAX([T].[COMPLETED_DATE]) ASC) AS [TaskOrder],
			MAX([LA].[LOGIN_ID]) [CREATED_BY],
			MAX([LA].[LOGIN_NAME]) [CREATED_BY_NAME],
			MAX([LO].[LOGIN_ID] )[ASSIGNED_TO],
			MAX([LO].[LOGIN_NAME]) [ASSIGNED_TO_NAME],
			MAX([CT].[COMPLETED_DATE]) [WAVE_FINISH_DATE],
			MAX([T].[WAREHOUSE_SOURCE]) [WAREHOUSE_ID]
			INTO [#TASK] FROM [FERCO].[OP_WMS_TASK_LIST] [T] 
			INNER JOIN [#COMPLETED_TASK] CT ON [CT].[WAVE_PICKING_ID] = [T].[WAVE_PICKING_ID]  
			INNER JOIN [FERCO].[OP_WMS_LOGINS] [LA] ON [LA].[LOGIN_ID] = [T].[TASK_OWNER]  
			INNER JOIN [FERCO].[OP_WMS_LOGINS] [LO] ON [LO].[LOGIN_ID] = [T].[TASK_ASSIGNEDTO]  
			WHERE [T].[WAVE_PICKING_ID] IS NOT NULL AND [T].[QUANTITY_ASSIGNED] <> [T].[QUANTITY_PENDING] 
			GROUP BY [T].[WAVE_PICKING_ID], [T].[MATERIAL_ID];
				
	SELECT [T].[WAVE_PICKING_ID] [Ola de Picking], 
			[h].[DOC_NUM] [Pedido], 
			[T].[CREATED_BY] [Creado por], 
			[T].[CREATED_BY_NAME] [Nombre Creado por],
			[T].[MATERIAL_ID] [Material],
			[M].[MATERIAL_NAME] [MATERIAL_NAME],
			[T].[QUANTITY_ASSIGNED] [Cantidad Asignada],
			[T].[ASSIGNED_TO] [Asignado A],
			[T].[ASSIGNED_TO_NAME] [Nombre Asignado A],
			FORMAT([T].[ASSIGNED_DATE], 'dd/MM/yyyy HH:mm:ss' ) [Fecha de asignación],
			FORMAT([T].[ACCEPTED_DATE], 'dd/MM/yyyy HH:mm:ss' ) [Fecha de aceptación Picking],
			FORMAT([T].[COMPLETED_DATE] , 'dd/MM/yyyy HH:mm:ss' ) [Fecha de completación Picking], 
			CONVERT(VARCHAR(12), DATEADD(MS,DATEDIFF(MS,[T].[ASSIGNED_DATE],[T].[ACCEPTED_DATE]),0),114) [Intervalo Creacion Aceptacion], 
			DATEDIFF(MINUTE, [T].[ASSIGNED_DATE],[T].[ACCEPTED_DATE]) [Intervalo Creacion Aceptacion(Minutos)],
			CONVERT(VARCHAR(12), DATEADD(MS,DATEDIFF(MS,ISNULL([T1].[COMPLETED_DATE],[T].[ACCEPTED_DATE]),[T].[COMPLETED_DATE]), 0), 114) [Tiempo Picking],
			DATEDIFF(MINUTE, ISNULL([T1].[COMPLETED_DATE],[T].[ACCEPTED_DATE]),[T].[COMPLETED_DATE]) [Tiempo Picking(Minutos)], 
			CONVERT(VARCHAR(12), DATEADD(MS,DATEDIFF(MS,[T].[ACCEPTED_DATE],[T].[WAVE_FINISH_DATE]),0), 114) [Tiempo Total Picking],
			DATEDIFF(MINUTE, [T].[ACCEPTED_DATE],[T].[WAVE_FINISH_DATE]) [Tiempo Total Picking(Minutos)], 
			CONVERT(VARCHAR(12), DATEADD(MS,DATEDIFF(MS, [T].[ASSIGNED_DATE],[T].[WAVE_FINISH_DATE]),0), 114) [Tiempo Total desde asignación], 
			DATEDIFF(MINUTE, [T].[ASSIGNED_DATE],[T].[WAVE_FINISH_DATE]) [Tiempo Total desde asignación(Minutos)],
			[T].[TaskOrder] [Orden Tarea],
			CASE 
			WHEN FORMAT([T].[COMPLETED_DATE], 'HH:mm') BETWEEN '05:00' AND '13:30' THEN 'AM'
			WHEN FORMAT([T].[COMPLETED_DATE], 'HH:mm') BETWEEN '13:31' AND '20:00' THEN 'PM'
			WHEN FORMAT([T].[COMPLETED_DATE], 'HH:mm') BETWEEN '20:01' AND '23:59' THEN 'NOCHE'
			WHEN FORMAT([T].[COMPLETED_DATE], 'HH:mm') BETWEEN '00:00' AND '04:00' THEN 'NOCHE'
			END AS Turno
			
			FROM [#TASK] [T]  
			LEFT JOIN [#TASK] [T1] ON [T].[WAVE_PICKING_ID] = [T1].[WAVE_PICKING_ID] AND [T1].[TaskOrder] + 1 = [T].[TaskOrder]  
			LEFT JOIN [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [h] ON [h].[WAVE_PICKING_ID] = [T].[WAVE_PICKING_ID] AND [h].[IS_CONSOLIDATED] = 0   
			INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [T].[MATERIAL_ID]
			WHERE T.ASSIGNED_DATE>=getdate()-30   AND T.ASSIGNED_DATE<=getdate()
			ORDER BY [T].[WAVE_PICKING_ID], [T].[TaskOrder]; 


END;