CREATE view view_Transacciones as
select  convert(varchar, [COMPLETED_DATE], 112) FECHAKEY,
WAREHOUSE_SOURCE,WAVE_PICKING_ID,TASK_ASSIGNEDTO,TASK_TYPE,TASK_SUBTYPE,
ASSIGNED_DATE,COMPLETED_DATE,SOURCE_TYPE,QUANTITY_ASSIGNED,IS_COMPLETED,IS_CANCELED
 from FERCO.OP_WMS_TASK_LIST 
where year(ASSIGNED_DATE) in (2020,2021,2022)
-- and WAVE_PICKING_ID = '34'