


CREATE VIEW [dbo].[VIEW_ERP_POWER_BI_SALES]
AS
SELECT  
        [FACTURA].[DocNum] [FACTURA],
        [FACTURA].[CardCode] [CODIGO_CL],
        [CLIENTE].[CardName] [NOMBRE_CL],
		[CLIENTE].[Address] [DIRECCION_CL],
		[FACTURA].[DocDate] [FECHA_FAC],
		[FACTURA].[DocCur] [DIVISA],
		[FACTURA].[SlpCode] [COD_VENDEDOR],
		VENDEDOR.[SlpName] [VENDEDOR],
		[CLIENTE].[ZipCode] [CODIGO_POSTAL],
		[CLIENTE].[County] [ID_REGION],
		ITEM.ItemCode [PRODUCTO],
		ITEM.ItemName DESCRIPCION,
		ITEM.SalUnitMsr [UNIDAD_MEDIDA],
		[DETALLE].[Quantity] [CANTIDAD],
		[DETALLE].[Price] [PRECIO_UNI],
		[DETALLE].[VatPrcnt] [PC_IMPUESTO],
		[DETALLE].[DiscPrcnt][PC_DESCUENTO],
		([DETALLE].[DiscPrcnt]*[DETALLE].[LineTotal])/100 [DESCUENTO],
		([DETALLE].[Quantity] * [DETALLE].[Price])[TOTAL],
		[DETALLE].[LineTotal] [TOTAL_NETO],
		[DETALLE].[ItemType] [GRUPO_SKU],
		[DETALLE].[VatGroup][GRUPO_INTERES]
FROM    [SAPSERVER].[SBOFERCO].dbo.[OINV] FACTURA
		INNER JOIN [SAPSERVER].[SBOFERCO].dbo.[INV1] DETALLE ON [DETALLE].[DocEntry] = [FACTURA].[DocEntry]
		INNER JOIN [SAPSERVER].[SBOFERCO].dbo.OITM ITEM ON ITEM.ItemCode = DETALLE.ItemCode
        INNER JOIN [SAPSERVER].[SBOFERCO].[dbo].[OSLP] VENDEDOR ON [VENDEDOR].[SlpCode] = [FACTURA].[SlpCode]
        INNER JOIN [SAPSERVER].[SBOFERCO].dbo.[OCRD] CLIENTE ON FACTURA.[CardCode] = [CLIENTE].[CardCode]
		WHERE [FACTURA].[DocDate] BETWEEN GETDATE()-90 AND GETDATE()






