

CREATE view [FERCO].[LICENCIAS_BLOQUEADAS] 
as
--select DISTINCT
--INX.LICENSE_ID,
--INX.MATERIAL_ID, 
--INX.QTY,
--INX.LOCKED_BY_INTERFACES, 
--L.CODIGO_POLIZA,
----TL.SERIAL_NUMBER,
--TL.WAVE_PICKING_ID,
--TL.TASK_TYPE,
--TL.ACCEPTED_DATE,
--PDH.IS_CONSOLIDATED,
----PDH.LAST_UPDATE,
--PDH.IS_POSTED_ERP,
--PDH.POSTED_RESPONSE,
--INX.IS_DISPATCH
-- from FERCO.OP_WMS_LICENSES L
-- INNER JOIN ferco.OP_WMS_INV_X_LICENSE INX ON (L.LICENSE_ID = INX.LICENSE_ID) 
--INNER JOIN FERCO.OP_WMS_TASK_LIST TL ON ( L.CODIGO_POLIZA = TL.CODIGO_POLIZA_SOURCE AND INX.MATERIAL_ID = TL.MATERIAL_ID)
--LEFT JOIN FERCO.OP_WMS_NEXT_PICKING_DEMAND_HEADER PDH ON (PDH.WAVE_PICKING_ID = TL.WAVE_PICKING_ID)

----INNER JOIN FERCO.OP_WMS_PASS_DETAIL PD ON (PD.WAVE_PICKING_ID = PDH.WAVE_PICKING_ID AND PD.MATERIAL_ID = INX.MATERIAL_ID)


--WHERE INX.LOCKED_BY_INTERFACES = 1 and INX.[STATUS] <> 'DISPATCH' AND INX.IS_BLOCKED = 0 AND INX.QTY > 0

SELECT DISTINCT OT.TASK_ID,
OT.TRANS_TYPE,
--RDH.LAST_UPDATE,
OT.TRANS_DATE,
RDH.IS_AUTHORIZED,
RDH.IS_POSTED_ERP,
RDH.POSTED_RESPONSE,
--RDD.MATERIAL_ID,
IL.LICENSE_ID,
IL.MATERIAL_ID,
IL.QTY
FROM
FERCO.OP_WMS_INV_X_LICENSE IL
LEFT JOIN FERCO.OP_WMS_TRANS OT ON (OT.LICENSE_ID = IL.LICENSE_ID)
LEFT JOIN FERCO.OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER RDH ON (RDH.TASK_ID = OT.TASK_ID)
WHERE   IL.LOCKED_BY_INTERFACES = 1 and IL.IS_DISPATCH IS NULL AND IL.QTY > 0 AND OT.TRANS_TYPE  IN (
'INGRESO_GENERAL',
'TRASLADO_GENERAL')
--ORDER BY OT.TRANS_DATE

