





CREATE VIEW [FERCO].[OP_WMS_VIEW_RECEPTION_ERROR]
AS
SELECT ERP_RECEPTION_DOCUMENT_HEADER_ID AS [RECEPCION_NO],[TYPE] AS [TIPO],CODE_SUPPLIER AS [CLIENTE],LAST_UPDATE AS [FECHA],POSTED_RESPONSE AS [RESPUESTA_ERP],DOC_NUM AS [DOC_SAP], DOC_ENTRY  FROM FERCO.OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER
  WHERE ATTEMPTED_WITH_ERROR = 5 AND IS_POSTED_ERP = -1 AND ERP_REFERENCE = ''


	





