
CREATE VIEW FERCO.OP_WMS_VIEW_RECEIVABLE_ACOUNT
AS
SELECT DISTINCT
  A.[CLIENT_CODE]
 ,ISNULL((SUM(B.DocTotal) - (SUM(B.PaidToDate) + SUM(B.DiscSum))), 0) AS [SALDO]
FROM [FERCO].[OP_WMS_VIEW_CLIENTS] AS A
LEFT OUTER JOIN SAPSERVER.SBOFERCO.dbo.OINV AS B
  ON B.CardCode COLLATE SQL_Latin1_General_CP1_CI_AS = A.CLIENT_CODE
GROUP BY A.CLIENT_CODE
