

CREATE VIEW [FERCO].[OP_WMS_VIEW_REALLOCATIONS]
AS
SELECT 
	TRANS_DATE			AS	FechaHora, 
	LOGIN_NAME			AS	Operador,
	TRANS_DESCRIPTION	AS	Tipo,
	SOURCE_LICENSE		AS	LicenciaOrigen,
	TARGET_LICENSE		AS	LicenciaDestino,
	SOURCE_LOCATION		AS	UbicacionOrigen,
	TARGET_LOCATION		AS	UbicacionDestino
FROM 
	FERCO.OP_WMS_TRANS 
WHERE 
	TRANS_TYPE IN ('REUBICACION_COMPLETA','REUBICACION_PARCIAL')
GROUP BY
	TRANS_DATE,			
	LOGIN_NAME,			
	TRANS_DESCRIPTION,
	SOURCE_LICENSE,		
	TARGET_LICENSE,		
	SOURCE_LOCATION,		
	TARGET_LOCATION		
