
--FERCO.OP_WMS_VIEW_COST_PICKING		--COSTO DE EXTRACCION
--FERCO.OP_WMS_VIEW_RELATED_SERVICES	--COSTO DE SERVICIOS RELACIONADOS
--FERCO.OP_WMS_VIEW_RECEIVABLE_ACOUNT	--COSTO DE CUENTAS POR COBRAR
CREATE VIEW FERCO.OP_WMS_VIEW_CLIENT_FACTORS
AS
SELECT DISTINCT
  A.[CLIENT_CODE]
 ,ISNULL(A.[CLIENT_NAME], 'N/A') AS CLIENT_NAME
 ,CONVERT(NUMERIC(18, 0), 12) AS TASK_LIST_ID
 ,CONVERT(NUMERIC(38, 6), ISNULL((ISNULL(B.SALDO, 0) + ISNULL(C.TOTAL, 0)), 0)) AS FACTOR1
 ,(ISNULL((SELECT
      SUM(TOTAL_VALOR)
    FROM [FERCO].[OP_WMS_VIEW_VALORIZACION_FISCAL]
    WHERE CLIENT_OWNER = A.CLIENT_CODE)
  , 0) - D.TOTAL) AS FACTOR2
 ,((ISNULL((SELECT
      SUM(TOTAL_VALOR)
    FROM [FERCO].[OP_WMS_VIEW_VALORIZACION_FISCAL]
    WHERE CLIENT_OWNER = A.CLIENT_CODE)
  , 0) - D.TOTAL) - ISNULL((ISNULL(B.SALDO, 0) + ISNULL(C.TOTAL, 0)), 0)) AS FACTOR3 -- 650) AS FACTOR3
FROM [FERCO].[OP_WMS_VIEW_CLIENTS] AS A
LEFT OUTER JOIN FERCO.OP_WMS_VIEW_RECEIVABLE_ACOUNT AS B
  ON A.CLIENT_CODE = B.CLIENT_CODE
LEFT OUTER JOIN FERCO.OP_WMS_VIEW_RELATED_SERVICES AS C
  ON A.CLIENT_CODE = C.CLIENT_CODE
LEFT OUTER JOIN FERCO.OP_WMS_VIEW_COST_PICKING AS D
  ON A.CLIENT_CODE = D.CLIENT_CODE
