



CREATE VIEW [FERCO].[OP_WMS_VIEW_AVAILABLE_VS_ERP]
AS
SELECT
	[A].[CURRENT_WAREHOUSE] AS [Bodega]
	,[A].[MATERIAL_ID] AS [Codigo]
	,[A].[MATERIAL_NAME] AS [Nombre]
	,[A].[QTY] AS [DispWMS]
	,ISNULL((SELECT TOP 1 
					[QTY_RESERVED]
				FROM
					[FERCO].[OP_WMS_FUNC_GET_INVENTORY_RESERVED_BY_WH_SKU_WITH_PENDING_ERP_SEND]([A].[CURRENT_WAREHOUSE],
											[A].[MATERIAL_ID])),
			0) AS [EnTareasWMS]
	,([A].[QTY]
		+ ISNULL((SELECT TOP 1 
						[QTY_RESERVED]
					FROM
						[FERCO].[OP_WMS_FUNC_GET_INVENTORY_RESERVED_BY_WH_SKU_WITH_PENDING_ERP_SEND]([A].[CURRENT_WAREHOUSE],
											[A].[MATERIAL_ID])),
					0)) AS [InvTotalWMS]
	,ISNULL((SELECT TOP 1 
					[X].[ON_HAND]
				FROM
					[SWIFT_INTERFACES_ONLINE_SV].[ferco].[ERP_VIEW_INVENTORY_ONLINE] [X]
				WHERE
					[X].[CODE_WAREHOUSE] = [A].[ERP_WAREHOUSE]
					AND [X].[CODE_SKU] = SUBSTRING([A].[MATERIAL_ID],
											CHARINDEX('/',
											[A].[MATERIAL_ID])
											+ 1,
											LEN([A].[MATERIAL_ID]))),
			0) AS [InvERP]
	,(ISNULL((SELECT TOP 1 
					[X].[ON_HAND]
				FROM
					[SWIFT_INTERFACES_ONLINE_SV].[ferco].[ERP_VIEW_INVENTORY_ONLINE] [X]
				WHERE
					[X].[CODE_WAREHOUSE] = [A].[ERP_WAREHOUSE]
					AND [X].[CODE_SKU] = SUBSTRING([A].[MATERIAL_ID],
											CHARINDEX('/',
											[A].[MATERIAL_ID])
											+ 1,
											LEN([A].[MATERIAL_ID]))),
				0) - ([A].[QTY]
						+ ISNULL((SELECT TOP 1 
										[QTY_RESERVED]
									FROM
										[FERCO].[OP_WMS_FUNC_GET_INVENTORY_RESERVED_BY_WH_SKU_WITH_PENDING_ERP_SEND]([A].[CURRENT_WAREHOUSE],
											[A].[MATERIAL_ID])),
									0))) AS [Diferencia]
FROM
	[FERCO].[OP_WMS_VIEW_INVENTORY_BY_WAREHOUSE_CLEAR] [A];




