
CREATE VIEW FERCO.OP_WMS_VIEW_INVENTORY_DETAIL_ALMGEN_HIST
AS
SELECT
  (SELECT
      CLIENT_NAME
    FROM FERCO.OP_WMS_VIEW_CLIENTS
    WHERE (CLIENT_CODE = B.CLIENT_OWNER COLLATE DATABASE_DEFAULT))
  AS CLIENT_NAME
 ,ISNULL
  ((SELECT TOP (1)
      NUMERO_ORDEN
    FROM FERCO.OP_WMS_POLIZA_HEADER AS C
    WHERE (CODIGO_POLIZA = B.CODIGO_POLIZA))
  , '0') AS NUMERO_ORDEN
 ,ISNULL
  ((SELECT TOP (1)
      NUMERO_DUA
    FROM FERCO.OP_WMS_POLIZA_HEADER AS C
    WHERE (CODIGO_POLIZA = B.CODIGO_POLIZA))
  , '0') AS NUMERO_DUA
 ,ISNULL
  ((SELECT TOP (1)
      CONVERT(VARCHAR(20), FECHA_LLEGADA) AS Expr1
    FROM FERCO.OP_WMS_POLIZA_HEADER AS C
    WHERE (CODIGO_POLIZA = B.CODIGO_POLIZA))
  , '0') AS FECHA_LLEGADA
 ,A.DDMMYYYY
 ,A.LICENSE_ID
 ,A.TERMS_OF_TRADE
 ,C.MATERIAL_ID
 ,C.BARCODE_ID
 ,A.BARCODE_ID AS ALTERNATE_BARCODE
 ,A.MATERIAL_NAME
 ,A.QTY
 ,B.CLIENT_OWNER
 ,B.REGIMEN
 ,B.CODIGO_POLIZA
 ,B.CURRENT_LOCATION
 ,ISNULL(C.VOLUME_FACTOR, 0) AS VOLUMEN
 ,ISNULL(C.VOLUME_FACTOR, 0) * A.QTY AS TOTAL_VOLUMEN
 ,B.LAST_UPDATED_BY
FROM FERCO.OP_WMS_INV_X_LICENSE_HIST AS A
INNER JOIN FERCO.OP_WMS_LICENSES AS B
  ON A.LICENSE_ID = B.LICENSE_ID
INNER JOIN FERCO.OP_WMS_MATERIALS AS C
  ON A.MATERIAL_ID = C.MATERIAL_ID
WHERE (B.REGIMEN = 'GENERAL')
