
CREATE VIEW [FERCO].[OP_WMS_VIEW_GET_CONSOLIDATE_WMS_INVENTORY_STATUS_BY_WH_PRUEBA]
AS
(SELECT
		SF.ZONE ,
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,SUM(CASE [LOCKED_BY_INTERFACES]
				WHEN 1 THEN [IL].[QTY]
				ELSE 0
				END) [INVENTORY_IN_RECEPTION]
		,SUM(CASE [LOCKED_BY_INTERFACES]
				WHEN 1 THEN 0
				ELSE [IL].[QTY]
				END) [AVAILABLE]
		,SUM(CASE	WHEN [S].[ZONE] = 'ZZ'  AND [LOCKED_BY_INTERFACES] = 0 THEN [IL].[QTY]
					ELSE 0
				END) [INV_ZZ]
				--,MAX([P].[RESERVADO]) [PICKED_PENDING_ERP]
		,MAX([P].[RESERVADO]) [PICKED_PENDING_ERP]
		,MAX([PWT].[RESERVADO]) [PICKED_PENDING_ERP_WT]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]

	FROM
		[FERCO].[OP_WMS_INV_X_LICENSE] [IL]

	INNER JOIN [FERCO].[OP_WMS_LICENSES] [L] ON [L].[LICENSE_ID] = [IL].[LICENSE_ID]
	     INNER JOIN FERCO.OP_WMS_SHELF_SPOTS SF ON SF.LOCATION_SPOT = L.CURRENT_LOCATION
	INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [IL].[MATERIAL_ID]
	INNER JOIN [FERCO].[OP_WMS_SHELF_SPOTS] [S] ON [S].[LOCATION_SPOT] = [L].[CURRENT_LOCATION]
	INNER JOIN [FERCO].[OP_WMS_WAREHOUSES] [W] ON [S].[WAREHOUSE_PARENT] = [W].[WAREHOUSE_ID]
	LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING] [P] ON [P].[MATERIAL_ID] = [IL].[MATERIAL_ID]
											AND [P].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
	LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING_WT] [PWT] ON [PWT].[MATERIAL_ID] = [IL].[MATERIAL_ID]
											AND [PWT].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
	WHERE
		[IL].[QTY] > 0
		AND [L].[CURRENT_LOCATION] IS NOT NULL
		AND [M].[NON_STORAGE] = 0
		AND [W].[WAREHOUSE_ID] = 'CEDI_ZONA_5'
		AND [L].[WAVE_PICKING_ID] IS NULL
		AND [M].[IS_MASTER_PACK] = 0
		
		
	GROUP BY
		SF.ZONE,
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]);

--UNION
--SELECT
--	[M].[MATERIAL_ID]
--	,[M].[MATERIAL_NAME]
--	,0 [INVENTORY_IN_RECEPTION]
--	,[FERCO].[OP_WMS_FN_GET_AVAILABLE_INVENTORY_TO_ASSAMBLE_FOR_MASTERPACK]([M].[MATERIAL_ID],
--											'CEDI_ZONA_5') [AVAILABLE]
--	,0 [INV_ZZ]
--	,SUM(ISNULL([PD].[QTY_IMPLODED], 0)) [PICKED_PENDING_ERP]
--	,0 [PICKED_PENDING_ERP_WT]
--	,'CEDI_ZONA_5'
--	,'01'
--FROM
--	[FERCO].[OP_WMS_MATERIALS] [M]
--LEFT JOIN [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL] [PD] ON [PD].[MATERIAL_ID] = [M].[MATERIAL_ID]
--											AND [PD].[QTY_IMPLODED] > 0
--LEFT JOIN [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [PH] ON [PH].[PICKING_DEMAND_HEADER_ID] = [PD].[PICKING_DEMAND_HEADER_ID]
--WHERE
--	[M].[IS_MASTER_PACK] = 1
--	AND [PD].[IS_POSTED_ERP] <> 1
--GROUP BY
--	[M].[MATERIAL_ID]
--	,[M].[MATERIAL_NAME];







