


/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [FERCO].[OP_WMS_VIEW_GET_CONSOLIDATE_WMS_INVENTORY_STATUS_BY_WH]
		WHERE MATERIAL_ID IN (
		'FERCO/P000195',
		'FERCO/P000196'
		,'FERCO/KIT000050')
		ORDER BY MATERIAL_ID
*/
-- =============================================
CREATE VIEW [FERCO].[OP_WMS_VIEW_GET_CONSOLIDATE_WMS_INVENTORY_STATUS_BY_WH_14]
AS
(SELECT 
MATERIAL_ID 
,MATERIAL_NAME
,SUM(INVENTORY_IN_RECEPTION) AS INVENTORY_IN_RECEPTION
,SUM([AVAILABLE]) AS [AVAILABLE]
,SUM([PICKED_PENDING_ERP])  AS [PICKED_PENDING_ERP]
,SUM([PICKED_PENDING_ERP_WT]) AS [PICKED_PENDING_ERP_WT]
,[CURRENT_WAREHOUSE]
,[ERP_WAREHOUSE]
FROM (
	SELECT 
		CASE WHEN [M].[IS_MASTER_PACK] = 0 THEN [IL].[MATERIAL_ID] 
		ELSE MD.MATERIAL_ID 
		END [MATERIAL_ID]
		, CASE WHEN [M].[IS_MASTER_PACK] = 0 THEN [M].[MATERIAL_NAME] 
		ELSE M2.MATERIAL_NAME
		END [MATERIAL_NAME]
		,SUM(CASE 
				WHEN [IL].[LOCKED_BY_INTERFACES] = 1 AND TL.TASK_TYPE = 'TAREA_RECEPCION' AND M.IS_MASTER_PACK = 0 THEN [IL].[QTY]
				WHEN [IL].[LOCKED_BY_INTERFACES] = 1 AND TL.TASK_TYPE = 'TAREA_RECEPCION' AND M.IS_MASTER_PACK = 1 THEN MD.QTY
				ELSE 0
				END )[INVENTORY_IN_RECEPTION]
		,SUM(CASE
               WHEN ISNULL([IL].[LOCKED_BY_INTERFACES], 0) = 1 THEN  0
			   WHEN ISNULL([IL].[LOCKED_BY_INTERFACES], 0) = 0 AND M.IS_MASTER_PACK = 1 THEN  MD.QTY
               ELSE
					([IL].[QTY])
					
			   END ) [AVAILABLE]
		,MAX([P].[RESERVADO]) [PICKED_PENDING_ERP]
		,ISNULL(MAX([PWT].[RESERVADO]), ISNULL([WPWT].[RESERVADO],0)) [PICKED_PENDING_ERP_WT]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]
	FROM
		[FERCO].[OP_WMS_INV_X_LICENSE] [IL]
		INNER JOIN [FERCO].[OP_WMS_LICENSES] [L] ON [L].[LICENSE_ID] = [IL].[LICENSE_ID]
		INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [IL].[MATERIAL_ID]
		INNER JOIN [FERCO].[OP_WMS_SHELF_SPOTS] [S] ON [S].[LOCATION_SPOT] = [L].[CURRENT_LOCATION]
		INNER JOIN [FERCO].[OP_WMS_WAREHOUSES] [W] ON [S].[WAREHOUSE_PARENT] = [W].[WAREHOUSE_ID]
		LEFT JOIN [FERCO].[OP_WMS_POLIZA_HEADER] [PH] ON ([PH].[CODIGO_POLIZA] = [L].[CODIGO_POLIZA])
		LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING] [P] ON [P].[MATERIAL_ID] = [IL].[MATERIAL_ID] 
												AND [P].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_SENDING_WT] [WPWT] ON [WPWT].[MATERIAL_ID] = [IL].[MATERIAL_ID]
												AND [WPWT].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING_WT] [PWT] ON [PWT].[MATERIAL_ID] = [IL].[MATERIAL_ID]
												AND [PWT].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		-- Inventario sin confirmar
		LEFT JOIN [FERCO].[OP_WMS_TASK_LIST] [TL] ON (
														CAST(TL.DOC_ID_SOURCE AS VARCHAR) = L.CODIGO_POLIZA
														)
		-- Para que no tome encuenta lo que ya despacho
		LEFT JOIN [FERCO].[OP_WMS_TASK_LIST] [#TL] ON ([L].[CODIGO_POLIZA] = [#TL].[CODIGO_POLIZA_TARGET] )
		LEFT JOIN [FERCO].[OP_WMS_PASS_DETAIL] [PD] ON ([#TL].[WAVE_PICKING_ID] = [PD].[WAVE_PICKING_ID])
		LEFT JOIN FERCO.[OP_WMS3PL_PASSES] PS ON (PD.PASS_HEADER_ID = PS.PASS_ID)
	
		-- Para que tome el inventario disponible
		LEFT JOIN [FERCO].[OP_WMS_FN_GET_COMMITED_INVENTORY_BY_LICENCE]() [CI]
				ON (
					   [IL].[MATERIAL_ID] = [CI].[MATERIAL_ID]
					   AND [L].[CLIENT_OWNER] = [CI].[CLIENT_OWNER]
					   AND [CI].[LICENCE_ID] = [IL].[LICENSE_ID]
				   )
		-- Trae los materiales especiales
		LEFT JOIN [FERCO].[OP_WMS_MASTER_PACK_HEADER] MH ON (MH.LICENSE_ID = L.LICENSE_ID AND MH.MATERIAL_ID = IL.MATERIAL_ID )
		LEFT JOIN FERCO.OP_WMS_MASTER_PACK_DETAIL MD ON (MD.MASTER_PACK_HEADER_ID = MH.MASTER_PACK_HEADER_ID)
		LEFT JOIN FERCO.OP_WMS_MATERIALS M2 ON (M2.MATERIAL_ID = MD.MATERIAL_ID)
		
	
	WHERE
		[IL].[QTY] > 0
		AND [IL].[STATUS] <> 'DISPATCH'
		AND [L].[CURRENT_LOCATION] IS NOT NULL
		AND [M].[NON_STORAGE] = 0
		AND [W].[WAREHOUSE_ID] = '14'
		AND [L].[WAVE_PICKING_ID] IS NULL
		--AND [M].[IS_MASTER_PACK] = 0
		AND PS.PASS_ID IS NULL
				
	GROUP BY
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]	
		,[WPWT].[RESERVADO]
		,[M].[IS_MASTER_PACK]
		,MD.MATERIAL_ID
		,M2.MATERIAL_NAME
) AS N1
 GROUP BY
		[MATERIAL_ID]
		,[MATERIAL_NAME]
		,[CURRENT_WAREHOUSE]
		,[ERP_WAREHOUSE]	
		,[CURRENT_WAREHOUSE]
,[ERP_WAREHOUSE]
		
		)
