













/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [FERCO].[OP_WMS_VIEW_GET_RECEPTION_PENDING]
*/
-- =============================================
CREATE VIEW [FERCO].[OP_WMS_VIEW_GET_RECEPTION_PENDING]
AS
(SELECT
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[IL].[QTY] [INVENTORY_IN_RECEPTION]
		,il.CREATED_DATE
		,il.LICENSE_ID
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]
	FROM
		[FERCO].[OP_WMS_INV_X_LICENSE] [IL]
		INNER JOIN [FERCO].[OP_WMS_LICENSES] [L] ON [L].[LICENSE_ID] = [IL].[LICENSE_ID]
		INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [IL].[MATERIAL_ID]
		INNER JOIN [FERCO].[OP_WMS_SHELF_SPOTS] [S] ON [S].[LOCATION_SPOT] = [L].[CURRENT_LOCATION]
		INNER JOIN [FERCO].[OP_WMS_WAREHOUSES] [W] ON [S].[WAREHOUSE_PARENT] = [W].[WAREHOUSE_ID]
		LEFT JOIN [FERCO].[OP_WMS_POLIZA_HEADER] [PH] ON ([PH].[CODIGO_POLIZA] = [L].[CODIGO_POLIZA])
		LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING] [P] ON [P].[MATERIAL_ID] = [IL].[MATERIAL_ID]
												AND [P].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING_WT] [PWT] ON [PWT].[MATERIAL_ID] = [IL].[MATERIAL_ID]
												AND [PWT].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
		-- Inventario sin confirmar
		LEFT JOIN [FERCO].[OP_WMS_TASK_LIST] [TL] ON (
														CAST(TL.DOC_ID_SOURCE AS VARCHAR) = L.CODIGO_POLIZA
														)
		-- Para que no tome encuenta el estado DISPATCH
		LEFT JOIN [FERCO].[OP_WMS_TASK_LIST] [#TL] ON ([L].[CODIGO_POLIZA] = [#TL].[CODIGO_POLIZA_TARGET] )
		LEFT JOIN [FERCO].[OP_WMS_PASS_DETAIL] [PD] ON ([#TL].[WAVE_PICKING_ID] = [PD].[WAVE_PICKING_ID])
		LEFT JOIN FERCO.[OP_WMS3PL_PASSES] PS ON (PD.PASS_HEADER_ID = PS.PASS_ID)

		-- Para que tome el inventario disponible
		LEFT JOIN [FERCO].[OP_WMS_FN_GET_COMMITED_INVENTORY_BY_LICENCE]() [CI]
				ON (
					   [IL].[MATERIAL_ID] = [CI].[MATERIAL_ID]
					   AND [L].[CLIENT_OWNER] = [CI].[CLIENT_OWNER]
					   AND [CI].[LICENCE_ID] = [IL].[LICENSE_ID]
				   )
	WHERE
		[IL].[QTY] > 0
		AND [IL].[STATUS] <> 'DISPATCH'
		AND [L].[CURRENT_LOCATION] IS NOT NULL
		AND [M].[NON_STORAGE] = 0
		--AND [W].[WAREHOUSE_ID] = 'CEDI_ZONA_5'
		AND [L].[WAVE_PICKING_ID] IS NULL
		--AND [M].[IS_MASTER_PACK] = 0
		AND PS.PASS_ID IS NULL
		and [IL].[LOCKED_BY_INTERFACES] = 1 AND TL.TASK_TYPE = 'TAREA_RECEPCION' 
	--GROUP BY
	--	[IL].[MATERIAL_ID]
	--	,[M].[MATERIAL_NAME]
	--	,[L].[CURRENT_WAREHOUSE]
	--	,[W].[ERP_WAREHOUSE]
	);

