
-- =============================================
-- Autor:					pablo.aguilar
-- Fecha de Creacion: 		25-Jun-18 @ Nexus-Team Sprint  
-- Description:			    

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [FERCO].[OP_WMS_VW_GET_TASK_WITH_PENDING_ERP_SENDING]
		where material = 'ferco/015089' and bodega = 'FERCO_MAZATE'
*/
-- =============================================
CREATE VIEW [FERCO].[OP_WMS_VW_GET_TASK_WITH_PENDING_ERP_SENDING]
AS
(
		SELECT
		[T].[WAREHOUSE_SOURCE] BODEGA
		,[T].[MATERIAL_ID] MATERIAL
		,T.LICENSE_ID_TARGET LICENCIA
		,T.LICENSE_ID_SOURCE LICENCIA_ORIGEN
		--,T.LOCATION_SPOT_SOURCE
		,T.LOCATION_SPOT_TARGET UBICACION
		,T.ACCEPTED_DATE FECHA_ACEPTADO
		,T.ASSIGNED_DATE FECHA_ASIGNACION
		,[T].[TASK_SUBTYPE] SUBTIPO_TAREA
		,T.COMPLETED_DATE FECHA_COMPLETADO
		,T.WAVE_PICKING_ID OLA_DE_PICKING
		,[T].[TASK_SUBTYPE] TIPO_DE_TAREA
		,t.DOC_ID_TARGET  DOCUMENTO
		--,PH.CODIGO_POLIZA 
		,[T].[QUANTITY_ASSIGNED] - [T].[QUANTITY_PENDING] [RESERVADO]
		FROM [FERCO].[OP_WMS_TASK_LIST] [T]
		INNER JOIN [FERCO].[OP_WMS_MATERIALS] M ON [M].[MATERIAL_ID] = [T].[MATERIAL_ID]
		WHERE
		--T.WAVE_PICKING_ID = 119047
		[T].[TASK_TYPE] = 'TAREA_PICKING'
		--AND [T].[TASK_SUBTYPE] <> 'DESPACHO_WT'
		AND [T].[IS_COMPLETED] = 1
		AND ([T].[IS_PAUSED] <> 3)
		AND ([T].[CANCELED_DATETIME] IS NULL)
		AND [T].[QUANTITY_ASSIGNED] - [T].[QUANTITY_PENDING] > 0
		--AND IXL.LOCKED_BY_INTERFACES = 1				
		AND [T].[WAVE_PICKING_ID] IN 
		(SELECT
		[H].[WAVE_PICKING_ID]	
		FROM [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_HEADER] [H]			
		WHERE [H].[WAVE_PICKING_ID] = [T].[WAVE_PICKING_ID]
		AND ISNULL([H].[IS_POSTED_ERP],0) <> 1)
)
