

/*
SELECT * FROM [FERCO].[OP_WMS_VIEW_AVAILABLE_VS_ERP_DETAIL] 
SELECT * FROM [FERCO].[OP_WMS_VIEW_AVAILABLE_VS_ERP]

*/

CREATE VIEW [FERCO].[OP_WMS_VIEW_AVAILABLE_VS_ERP_DETAIL]
AS
SELECT
	[A].[CURRENT_WAREHOUSE] AS [Bodega]
	,[A].[MATERIAL_ID] AS [Codigo]
	,[A].[MATERIAL_NAME] AS [Nombre]
	,[A].[CURRENT_LOCATION] [Location]
	,[A].[LICENSE_ID] [License]
	,ISNULL([A].[AVAILABLE], 0) AS [DispWMS]
	,ISNULL([A].[INVENTORY_IN_RECEPTION], 0) [En Recepción]
	,ISNULL([A].[PICKED_PENDING_ERP], 0) [En Picking]
	,ISNULL([A].[AVAILABLE], 0)
	+ ISNULL([A].[INVENTORY_IN_RECEPTION], 0)
	+ ISNULL([A].[PICKED_PENDING_ERP], 0) [Total Wms]
	,ISNULL([X].[ON_HAND], 0) [Inv ERP]
	,[A].[Pendiente De envio]
	,[A].[Fuente]
	,[A].[Ola]
FROM
	[FERCO].[OP_WMS_VIEW_GET_DETAILED_WMS_INVENTORY_STATUS_BY_WH] [A]
LEFT JOIN [SWIFT_INTERFACES_ONLINE_SV].[ferco].[ERP_VIEW_INVENTORY_ONLINE_WS_01] [X] ON (
											[X].[CODE_WAREHOUSE] = [A].[ERP_WAREHOUSE]
											AND [X].[CODE_SKU] = [FERCO].[OP_WMS_FN_SPLIT_COLUMNS]([A].[MATERIAL_ID],
											2, '/')
											);

	
	 






