CREATE VIEW [FERCO].[OP_WMS_VIEW_GET_CONSOLIDATE_WMS_INVENTORY_STATUS_BY_WH_CUARENTENA_CEDI]
AS
(SELECT
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,SUM(CASE [LOCKED_BY_INTERFACES]
				WHEN 1 THEN [IL].[QTY]
				ELSE 0
				END) [INVENTORY_IN_RECEPTION]
		,SUM(CASE [LOCKED_BY_INTERFACES]
				WHEN 1 THEN 0
				ELSE [IL].[QTY]
				END) [AVAILABLE]
	--	,SUM(CASE	WHEN [S].[ZONE] = 'ZZ' -- AND [LOCKED_BY_INTERFACES] = 0 
	--			THEN [IL].[QTY]
	--				ELSE 0
	--			END) [INV_ZZ]
				--,MAX([P].[RESERVADO]) [PICKED_PENDING_ERP]
		,MAX([P].[RESERVADO]) [PICKED_PENDING_ERP]
		,MAX([PWT].[RESERVADO]) [PICKED_PENDING_ERP_WT]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]
	FROM
		[FERCO].[OP_WMS_INV_X_LICENSE] [IL]
	INNER JOIN [FERCO].[OP_WMS_LICENSES] [L] ON [L].[LICENSE_ID] = [IL].[LICENSE_ID]
	INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [IL].[MATERIAL_ID]
	INNER JOIN [FERCO].[OP_WMS_SHELF_SPOTS] [S] ON [S].[LOCATION_SPOT] = [L].[CURRENT_LOCATION]
	INNER JOIN [FERCO].[OP_WMS_WAREHOUSES] [W] ON [S].[WAREHOUSE_PARENT] = [W].[WAREHOUSE_ID]
	LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING] [P] ON [P].[MATERIAL_ID] = [IL].[MATERIAL_ID]
											AND [P].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
	LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_WITH_PENDING_ERP_SENDING_WT] [PWT] ON [PWT].[MATERIAL_ID] = [IL].[MATERIAL_ID]
											AND [PWT].[WAREHOUSE_SOURCE] = [W].[WAREHOUSE_ID]
	WHERE
		[IL].[QTY] > 0
		AND [L].[CURRENT_LOCATION] IS NOT NULL
		AND [M].[NON_STORAGE] = 0
		AND [W].[WAREHOUSE_ID] = 'CUARENTENA_CEDI'
		AND [L].[WAVE_PICKING_ID] IS NULL
		AND [M].[IS_MASTER_PACK] = 0
		
		
	GROUP BY
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE])