

-- =============================================
-- Autor:					alex.carrillo
-- Fecha de Creacion: 		08-19-2020 
-- Description:			    vista para estado de olas

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [FERCO].[OP_WMS_VIEW_PICKING_STATUS]
*/
-- =============================================
CREATE VIEW [FERCO].[OP_WMS_VIEW_PICKING_STATUS]
AS
(SELECT DISTINCT
CASE WHEN PDH.WAVE_PICKING_ID IS NOT NULL THEN 'DEMANDA DE DESPACHO NO.' + CAST(PDH.WAVE_PICKING_ID AS VARCHAR)
END AS DESPACHO ,
PDH.WAVE_PICKING_ID AS OLA_PICKING,
PDH.DOC_NUM AS NUMERO_ORDEN_VENTA_SAP,
--PD.PASS_HEADER_ID AS NUMERO_PASE,
PDH.CREATED_DATE AS FECHA_CREACION,
PDH.CLIENT_CODE AS CODIGO_CLIENTE,
PDH.CLIENT_NAME AS NOMBRE_CLIENTE,
TL.MATERIAL_ID AS CODIGO_MATERIAL,
--SUM(PDD.QTY) AS CANTIDAD_TAREA,
SUM(TL.QUANTITY_ASSIGNED) AS CANTIDAD_TAREA,
SUM(TL.QUANTITY_PENDING) AS CANTIDAD_PENDIENTE,
--CASE WHEN PDD.IS_POSTED_ERP = 1 THEN 'MATERIAL ENVIADO A SAP'
--ELSE  'NO ENVIADO'
--END AS ENVIO_MATERIAL_SAP , 
PDD.ERP_REFERENCE AS REFERENCIA_MATERIAL_SAP ,
CASE 
WHEN MAX(TL.IS_COMPLETED) = 1 AND SUM(TL.QUANTITY_PENDING) > 0 THEN 'TAREA PARCIAL COMPLETA'
WHEN MAX(TL.IS_COMPLETED) = 1 AND SUM(TL.QUANTITY_PENDING) = 0 THEN 'COMPLETA'
ELSE  'INCOMPLETA'
END AS ESTADO_DE_LA_TAREA  , 
CASE WHEN PDH.IS_AUTHORIZED = 1 THEN 'AUTORIZADA'
ELSE  'NO AUTORIZADA'
END AS AUTORIZACION ,
CASE 
WHEN PDD.ERP_REFERENCE <> '' OR PDD.ERP_REFERENCE <> NULL THEN 'ENVIADO'
ELSE  'NO ENVIADO'
END AS ENVIO_A_SAP,
CASE WHEN PDD.POSTED_RESPONSE LIKE '%error%' AND PDD.ERP_REFERENCE <> '' OR PDD.ERP_REFERENCE <> NULL THEN 'Se creo La Nota de Entrega en El ERP NO:' + CAST(PDD.ERP_REFERENCE AS VARCHAR) + ' | ' + 'Creado Exitosamente' 
ELSE PDD.POSTED_RESPONSE 
END AS RESPUESTA_SAP,
PDH.ERP_REFERENCE AS DOCUMENTO_GENERADO_SAP,
TL.TASK_SUBTYPE AS TIPO_TAREA
FROM FERCO.OP_WMS_NEXT_PICKING_DEMAND_DETAIL PDD --FERCO.OP_WMS_NEXT_PICKING_DEMAND_HEADER PDH
INNER JOIN FERCO.OP_WMS_NEXT_PICKING_DEMAND_HEADER PDH ON (PDH.PICKING_DEMAND_HEADER_ID = PDD.PICKING_DEMAND_HEADER_ID)
INNER JOIN ferco.OP_WMS_TASK_LIST TL ON (TL.WAVE_PICKING_ID = PDH.WAVE_PICKING_ID)
--WHERE TL.TASK_SUBTYPE IN ('DESPACHO_CONSOLIDADO',
--'DESPACHO_GENERAL')
GROUP BY PDH.WAVE_PICKING_ID
,PDH.DOC_NUM
,PDH.CREATED_DATE 
,PDH.CLIENT_CODE  
,PDH.CLIENT_NAME 
,TL.MATERIAL_ID
--,PDD.QTY 
--,TL.QUANTITY_ASSIGNED
--,TL.QUANTITY_PENDING
,PDD.POSTED_RESPONSE
,PDD.IS_POSTED_ERP
,PDD.ERP_REFERENCE
--,TL.IS_COMPLETED
,PDH.IS_AUTHORIZED
,PDH.IS_POSTED_ERP
,PDH.POSTED_RESPONSE
,PDH.ERP_REFERENCE
,TL.TASK_SUBTYPE




);





