-- =============================================
-- Autor:					pablo.aguilar
-- Fecha de Creacion: 		25-Jun-18 @ Nexus-Team Sprint  
-- Description:			    

/*
-- Ejemplo de Ejecucion:
        SELECT * FROM [FERCO].[OP_WMS_VIEW_GET_DETAILED_WMS_INVENTORY_STATUS_BY_WH]
*/
-- =============================================
CREATE VIEW [FERCO].[OP_WMS_VIEW_GET_DETAILED_WMS_INVENTORY_STATUS_BY_WH]
AS
(SELECT
		[IL].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[L].[CURRENT_LOCATION]
		,[L].[LICENSE_ID]
		,CASE [LOCKED_BY_INTERFACES]
			WHEN 1 THEN [QTY]
			ELSE 0
			END [INVENTORY_IN_RECEPTION]
		,CASE [LOCKED_BY_INTERFACES]
			WHEN 1 THEN 0
			ELSE [QTY]
			END [AVAILABLE]
		,[L].[CURRENT_WAREHOUSE]
		,[W].[ERP_WAREHOUSE]
		,0 [PICKED_PENDING_ERP]
		,[IL].[LOCKED_BY_INTERFACES] [Pendiente De envio]
		,'Inventario' [Fuente]
		,CASE [LOCKED_BY_INTERFACES]
			WHEN 1 THEN  (SELECT TOP 1 [R].[TASK_ID] FROM [FERCO].[OP_WMS_ERP_RECEPTION_DOCUMENT_HEADER] R WHERE [R].[DOC_ID_POLIZA] = [L].[CODIGO_POLIZA])
			ELSE -1
			END  [Ola]
	FROM
		[FERCO].[OP_WMS_INV_X_LICENSE] [IL]
	INNER JOIN [FERCO].[OP_WMS_LICENSES] [L] ON [L].[LICENSE_ID] = [IL].[LICENSE_ID]
	INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [IL].[MATERIAL_ID]
	INNER JOIN [FERCO].[OP_WMS_WAREHOUSES] [W] ON [W].[WAREHOUSE_ID] = [L].[CURRENT_WAREHOUSE]
	--LEFT JOIN [FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_DETAIL_WITH_PENDING_ERP_SENDING] P ON P.[LICENSE_ID_SOURCE] = [IL].[LICENSE_ID] AND P.[MATERIAL_ID] = IL.[MATERIAL_ID]
	WHERE
		[QTY] > 0
		AND [L].[CURRENT_LOCATION] IS NOT NULL
		AND [L].[WAVE_PICKING_ID] IS NULL
		AND [W].[WAREHOUSE_ID] = 'CEDI_ZONA_5'
	UNION
	SELECT
		[P].[MATERIAL_ID]
		,[M].[MATERIAL_NAME]
		,[P].[Destino]
		, p.[LICENSE_ID_SOURCE]
		, 0 [INVENTORY_IN_RECEPTION]
		,0[AVAILABLE]
		, p.[WAREHOUSE_SOURCE]
		, w.[ERP_WAREHOUSE]
		,[P].[RESERVADO] [PICKED_PENDING_ERP]		
		,[P].[Pendiente De envio]
		,[P].[Fuente]
		,[P].[Ola]
	FROM
		[FERCO].[OP_WMS_VW_GET_PICKED_INVENTORY_DETAIL_WITH_PENDING_ERP_SENDING] [P]
	INNER JOIN [FERCO].[OP_WMS_MATERIALS] [M] ON [M].[MATERIAL_ID] = [P].[MATERIAL_ID]
	INNER JOIN [FERCO].[OP_WMS_WAREHOUSES] [W] ON [W].[WAREHOUSE_ID] = p.[WAREHOUSE_SOURCE]);



