


-- =============================================
-- Autor:					Brandon Sicay
-- Fecha de Creacion: 		2022-01-20 
-- Description:			    Vista que trae el inventario disponible por bodega

/*
-- Ejemplo de Ejecucion:
		SELECT * FROM [FERCO].[OP_WMS_VIEW_PWBI_COMPLETED_TASK]
*/
-- =============================================

CREATE VIEW [FERCO].[OP_WMS_VIEW_PWBI_TASK]
AS


	SELECT [T].[WAVE_PICKING_ID],
			[T].[MATERIAL_ID],
			SUM([T].[QUANTITY_ASSIGNED]) [QUANTITY_ASSIGNED],
			MAX([T].[ASSIGNED_DATE]) [ASSIGNED_DATE],
			MAX([T].[ACCEPTED_DATE]) [ACCEPTED_DATE],
			MAX([T].[COMPLETED_DATE]) [COMPLETED_DATE],
			RANK() OVER (PARTITION BY [T].[WAVE_PICKING_ID] ORDER BY MAX([T].[COMPLETED_DATE]) ASC) AS [TaskOrder],
			MAX([LA].[LOGIN_ID]) [CREATED_BY],
			MAX([LA].[LOGIN_NAME]) [CREATED_BY_NAME],
			MAX([LO].[LOGIN_ID] )[ASSIGNED_TO],
			MAX([LO].[LOGIN_NAME]) [ASSIGNED_TO_NAME],
			MAX([CT].[COMPLETED_DATE]) [WAVE_FINISH_DATE],
			MAX([T].[WAREHOUSE_SOURCE]) [WAREHOUSE_ID],
			[T].[TASK_TYPE][TIPO_TAREA]
			FROM [FERCO].[OP_WMS_TASK_LIST] [T] 
			INNER JOIN [FERCO].[OP_WMS_VIEW_PWBI_COMPLETED_TASK] CT ON [CT].[WAVE_PICKING_ID] = [T].[WAVE_PICKING_ID]  
			INNER JOIN [FERCO].[OP_WMS_LOGINS] [LA] ON [LA].[LOGIN_ID] = [T].[TASK_OWNER]  
			INNER JOIN [FERCO].[OP_WMS_LOGINS] [LO] ON [LO].[LOGIN_ID] = [T].[TASK_ASSIGNEDTO]  
			WHERE [T].[WAVE_PICKING_ID] IS NOT NULL AND [T].[QUANTITY_ASSIGNED] <> [T].[QUANTITY_PENDING] 
			GROUP BY [T].[WAVE_PICKING_ID], [T].[MATERIAL_ID], [T].[TASK_TYPE];


