

-- Modificacion 8/9/2017 @ NEXUS-Team Sprint Banjo-Kazooie
-- rodrigo.gomez
-- Se agrega un union a la tabla de OP_WMS_COMPANY

-- Modificacion 8/29/2017 @ NEXUS-Team Sprint CommandAndConquer
-- rodrigo.gomez
-- Se agrega UNION a la tabla OP_SETUP_COMPANY

-- SELECT * FROM [FERCO].[OP_WMS_VIEW_CLIENTS]

CREATE VIEW [FERCO].[OP_WMS_VIEW_CLIENTS]
AS
--SELECT     CLIENT_CODE, CLIENT_NAME, CLIENT_ROUTE, CLIENT_CLASS, CLIENT_STATUS, CLIENT_REGION, CLIENT_ADDRESS, CLIENT_PHONE, CLIENT_CA, 
--                      ISNULL
--                          ((SELECT     CONVERT(VARCHAR(10), CLIENT_CODE) AS Expr1
--                              FROM         [FERCO].OP_WMS_CLIENTS AS B
--                              WHERE     (CLIENT_CODE = A.CLIENT_ERP_CODE)), '') AS CLIENT_ERP_CODE
--FROM         [FERCO].OP_WMS_CLIENTS AS A
		--,1 [IS_ACTIVE]
		--,0 [CAN_EDIT]

--SELECT
--	[CardCode] COLLATE DATABASE_DEFAULT AS [CLIENT_CODE]
--	,[CardName] COLLATE DATABASE_DEFAULT AS [CLIENT_NAME]
--	,'N/A' AS [CLIENT_ROUTE]
--	,'AAA' AS [CLIENT_CLASS]
--	,1 AS [CLIENT_STATUS]
--	,'' AS [CLIENT_REGION]
--	,'' AS [CLIENT_ADDRESS]
--	,'9999' AS [CLIENT_CA]
--	,[CardCode] COLLATE DATABASE_DEFAULT AS [CLIENT_ERP_CODE]
		--,1 [IS_ACTIVE]
		--,0 [CAN_EDIT]
--FROM
--	[FERCO].[OP_WMS_SAP_CLIENTS]
--UNION
SELECT
  [CLIENT_CODE]
 ,[COMPANY_NAME] [CLIENT_NAME]
 ,'N/A' AS [CLIENT_ROUTE]
 ,'AAA' AS [CLIENT_CLASS]
 ,1 AS [CLIENT_STATUS]
 ,'' AS [CLIENT_REGION]
 ,'' AS [CLIENT_ADDRESS]
 , CAST( (SELECT TOP 1 [c].[ACUERDO_COMERCIAL] FROM [FERCO].[OP_WMS_ACUERDOS_X_CLIENTE] c WHERE c.[CLIENT_ID] = co.[CLIENT_CODE] )  AS VARCHAR) AS [CLIENT_CA]
 ,[MASTER_ID_CLIENT_CODE] [CLIENT_ERP_CODE]
		,1 [IS_ACTIVE]
		,0 [CAN_EDIT]
FROM [FERCO].[OP_WMS_COMPANY] co

WHERE [COMPANY_ID] > 0
--UNION ALL
--SELECT 
--	[COMPANY_CODE] [CLIENT_CODE]
--	,[COMPANY_NAME] [CLIENT_NAME]
--	,'N/A' AS [CLIENT_ROUTE]
--	,'AAA' AS [CLIENT_CLASS]
--	,1 AS [CLIENT_STATUS]
--	,'' AS [CLIENT_REGION]
--	,'' AS [CLIENT_ADDRESS]
--	,'9999' AS [CLIENT_CA]
--	,[COMPANY_CODE] COLLATE DATABASE_DEFAULT AS [CLIENT_ERP_CODE]
		--,1 [IS_ACTIVE]
		--,0 [CAN_EDIT]
--FROM [FERCO].[OP_SETUP_COMPANY]
--UNION
--SELECT
--  CARDCODE COLLATE DATABASE_DEFAULT [CLIENT_CODE]
-- ,CARDNAME COLLATE DATABASE_DEFAULT [CLIENT_NAME]
-- ,'N/A' AS [CLIENT_ROUTE]
-- ,'AAA' AS [CLIENT_CLASS]
-- ,1 AS [CLIENT_STATUS]
-- ,'' AS [CLIENT_REGION]
-- ,'' AS [CLIENT_ADDRESS]
-- ,'9999' AS [CLIENT_CA]
-- ,CARDCODE COLLATE DATABASE_DEFAULT [CLIENT_ERP_CODE]
--		,1 [IS_ACTIVE]
--		,0 [CAN_EDIT]
--FROM SAPSERVER.[SBOPruebas].DBO.[OCRD]
--WHERE [U_CLIENTEWMS] = 'Y'
