

CREATE view [FERCO].[PICKING_MANUAL] 
as
SELECT DISTINCT 
PDH.WAVE_PICKING_ID AS OLA_PICKING,
PDH.DOC_ENTRY,
PDH.CREATED_DATE AS FECHA_CREACION,
PDD.MATERIAL_ID AS MATERIAL,
PDD.QTY AS CANTIDAD_PICKING,
TL.TASK_OWNER AS SUPERVISOR,
--TL.TASK_ASSIGNEDTO AS OPERADOR,
--TL.QUANTITY_ASSIGNED,
--TL.QUANTITY_PENDING,
PDH.POSTED_RESPONSE AS RESPUESTA_ERP,
TL.TASK_TYPE AS TIPO_TAREA,
--INL.LICENSE_ID,
tl.CODIGO_POLIZA_TARGET AS CODIGO_POLIZA
FROM FERCO.OP_WMS_NEXT_PICKING_DEMAND_HEADER PDH
INNER JOIN FERCO.OP_WMS_TASK_LIST TL ON (TL.WAVE_PICKING_ID = PDH.WAVE_PICKING_ID)
INNER JOIN FERCO.OP_WMS_NEXT_PICKING_DEMAND_DETAIL PDD ON (PDH.PICKING_DEMAND_HEADER_ID = PDD.PICKING_DEMAND_HEADER_ID)
INNER JOIN FERCO.OP_WMS_LICENSES L ON ( TL.CODIGO_POLIZA_TARGET = L.CODIGO_POLIZA )
inner join ferco.OP_WMS_INV_X_LICENSE INL ON (L.LICENSE_ID = INL.LICENSE_ID and pdd.MATERIAL_ID = inl.MATERIAL_ID)
WHERE  PDH.POSTED_RESPONSE like '%MANUAL%' 

