CREATE TABLE [FERCO].[OP_SETUP_COMPANY] (
    [BACKOFFICE_LICENSE] VARCHAR (50)  NOT NULL,
    [COMPANY_NAME]       VARCHAR (150) NOT NULL,
    [COMPANY_CODE]       VARCHAR (25)  NULL,
    [LOGO]               VARCHAR (MAX) NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_OP_SETUP_CODE_NAME]
    ON [FERCO].[OP_SETUP_COMPANY]([COMPANY_CODE] ASC)
    INCLUDE([COMPANY_NAME]);

