CREATE TABLE [FERCO].[OP_WMS_PHYSICAL_COUNTS_HEADER] (
    [PHYSICAL_COUNT_HEADER_ID] INT           IDENTITY (1, 1) NOT NULL,
    [TASK_ID]                  INT           NULL,
    [REGIMEN]                  VARCHAR (50)  NULL,
    [DISTRIBUTION_CENTER]      VARCHAR (200) NULL,
    [STATUS]                   VARCHAR (25)  NULL,
    PRIMARY KEY CLUSTERED ([PHYSICAL_COUNT_HEADER_ID] ASC),
    CONSTRAINT [FK_TASK_ID] FOREIGN KEY ([TASK_ID]) REFERENCES [FERCO].[OP_WMS_TASK] ([TASK_ID])
);

