CREATE TABLE [FERCO].[OP_WMS_CLIENT] (
    [CLIENT_ID]       INT           IDENTITY (1, 1) NOT NULL,
    [CLIENT_CODE]     VARCHAR (50)  NOT NULL,
    [CLIENT_NAME]     VARCHAR (250) NOT NULL,
    [IS_ACTIVE]       INT           CONSTRAINT [DF_OP_WMS_CLIENT_IS_ACTIVE] DEFAULT ((0)) NOT NULL,
    [CLIENT_CODE_ERP] VARCHAR (50)  NULL,
    CONSTRAINT [PK_OP_WMS_CLIENT] PRIMARY KEY CLUSTERED ([CLIENT_ID] ASC),
    CONSTRAINT [CH_OP_WMS_CLIENT_IS_ACTIVE] CHECK ([IS_ACTIVE]=(1) OR [IS_ACTIVE]=(0)),
    CONSTRAINT [UC_OP_WMS_CLIENT_CLIENT_CODE] UNIQUE NONCLUSTERED ([CLIENT_CODE] ASC)
);

