CREATE TABLE [FERCO].[OP_WMS_DELIVERED_DISPATCH_DETAIL] (
    [DELIVERED_DISPATCH_DETAIL_ID] INT          IDENTITY (1, 1) NOT NULL,
    [LABEL_ID]                     INT          NULL,
    [LAST_UPDATE]                  DATETIME     NULL,
    [LAST_UPDATE_BY]               VARCHAR (50) NULL,
    [DELIVERED_DISPATCH_HEADER_ID] INT          NULL,
    PRIMARY KEY CLUSTERED ([DELIVERED_DISPATCH_DETAIL_ID] ASC),
    FOREIGN KEY ([DELIVERED_DISPATCH_HEADER_ID]) REFERENCES [FERCO].[OP_WMS_DELIVERED_DISPATCH_HEADER] ([DELIVERED_DISPATCH_HEADER_ID]),
    FOREIGN KEY ([LABEL_ID]) REFERENCES [FERCO].[OP_WMS_PICKING_LABELS] ([LABEL_ID])
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_DELIVERED_DISPATCH_DETAIL_DELIVERED_DISPATCH_HEADER_ID]
    ON [FERCO].[OP_WMS_DELIVERED_DISPATCH_DETAIL]([DELIVERED_DISPATCH_HEADER_ID] ASC)
    INCLUDE([DELIVERED_DISPATCH_DETAIL_ID], [LABEL_ID], [LAST_UPDATE], [LAST_UPDATE_BY]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_DELIVERED_DISPATCH_DETAIL_LABEL_ID]
    ON [FERCO].[OP_WMS_DELIVERED_DISPATCH_DETAIL]([LABEL_ID] ASC);

