CREATE TABLE [FERCO].[OP_WMS_DOC_STATUS] (
    [ID_STATUS]          INT          IDENTITY (1, 1) NOT NULL,
    [DESCRIPTION_STATUS] VARCHAR (50) DEFAULT ('') NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_STATUS] ASC),
    UNIQUE NONCLUSTERED ([DESCRIPTION_STATUS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_OP_WMS_DOC_STATUS_ID_STATUS]
    ON [FERCO].[OP_WMS_DOC_STATUS]([ID_STATUS] ASC)
    INCLUDE([DESCRIPTION_STATUS]);

