CREATE TABLE [FERCO].[OP_WMS_COMPONENTS_BY_MASTER_PACK] (
    [MASTER_PACK_COMPONENT_ID] INT          IDENTITY (1, 1) NOT NULL,
    [MASTER_PACK_CODE]         VARCHAR (50) NOT NULL,
    [COMPONENT_MATERIAL]       VARCHAR (50) NOT NULL,
    [QTY]                      INT          NOT NULL,
    CONSTRAINT [PK_OP_WMS_COMPONENTS_BY_MASTER_PACK_PRIMARY] PRIMARY KEY CLUSTERED ([MASTER_PACK_COMPONENT_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_COMPONENTS_BY_MASTER_PACK_COMPONENT_MATERIAL]
    ON [FERCO].[OP_WMS_COMPONENTS_BY_MASTER_PACK]([COMPONENT_MATERIAL] ASC)
    INCLUDE([MASTER_PACK_CODE]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_COMPONENTS_BY_MASTER_PACK_MASTER_PACK_CODE]
    ON [FERCO].[OP_WMS_COMPONENTS_BY_MASTER_PACK]([MASTER_PACK_CODE] ASC, [COMPONENT_MATERIAL] ASC)
    INCLUDE([QTY]);

