CREATE TABLE [FERCO].[OP_WMS_DEVICE] (
    [DEVICE_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [MANUFACTURER] VARCHAR (25)  NOT NULL,
    [MODEL]        VARCHAR (125) NOT NULL,
    [DESCRIPTION]  VARCHAR (125) NULL,
    PRIMARY KEY CLUSTERED ([DEVICE_ID] ASC),
    CONSTRAINT [U_MANUFACTURER_MODEL] UNIQUE NONCLUSTERED ([MANUFACTURER] ASC, [MODEL] ASC)
);

