CREATE TABLE [FERCO].[OP_WMS_ZONE] (
    [ZONE_ID]                    INT           IDENTITY (1, 1) NOT NULL,
    [ZONE]                       VARCHAR (50)  NOT NULL,
    [DESCRIPTION]                VARCHAR (100) DEFAULT ('') NOT NULL,
    [WAREHOUSE_CODE]             VARCHAR (25)  NOT NULL,
    [RECEIVE_EXPLODED_MATERIALS] INT           NOT NULL,
    [LINE_ID]                    VARCHAR (25)  NOT NULL,
    CONSTRAINT [PK_OP_WMS_ZONE] PRIMARY KEY CLUSTERED ([ZONE_ID] ASC),
    CONSTRAINT [CH_RECEIVE_EXPLODED_MATERIALS_0] CHECK ([RECEIVE_EXPLODED_MATERIALS]=(1) OR [RECEIVE_EXPLODED_MATERIALS]=(0))
);


GO
CREATE NONCLUSTERED INDEX [IDX_OP_WMS_ZONE_TO]
    ON [FERCO].[OP_WMS_ZONE]([ZONE] ASC, [WAREHOUSE_CODE] ASC, [LINE_ID] ASC);

