CREATE TABLE [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL] (
    [PICKING_DEMAND_DETAIL_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PICKING_DEMAND_HEADER_ID] INT             NOT NULL,
    [MATERIAL_ID]              VARCHAR (50)    NOT NULL,
    [QTY]                      DECIMAL (18, 4) NULL,
    [LINE_NUM]                 INT             DEFAULT ((-1)) NOT NULL,
    [ERP_OBJECT_TYPE]          INT             NULL,
    [PRICE]                    NUMERIC (18, 6) DEFAULT ((0.0)) NOT NULL,
    [WAS_IMPLODED]             INT             DEFAULT ((0)) NOT NULL,
    [QTY_IMPLODED]             INT             DEFAULT ((0)) NOT NULL,
    [MASTER_ID_MATERIAL]       VARCHAR (50)    NULL,
    [MATERIAL_OWNER]           VARCHAR (50)    NULL,
    [ATTEMPTED_WITH_ERROR]     INT             DEFAULT ((0)) NOT NULL,
    [IS_POSTED_ERP]            INT             DEFAULT ((0)) NOT NULL,
    [POSTED_ERP]               DATETIME        NULL,
    [ERP_REFERENCE]            VARCHAR (50)    NULL,
    [POSTED_STATUS]            VARCHAR (50)    NULL,
    [POSTED_RESPONSE]          VARCHAR (4000)  NULL,
    [INNER_SALE_STATUS]        VARCHAR (50)    NULL,
    [INNER_SALE_RESPONSE]      VARCHAR (1000)  NULL,
    [TONE]                     VARCHAR (20)    NULL,
    [CALIBER]                  VARCHAR (20)    NULL,
    [DISCOUNT]                 DECIMAL (18, 6) DEFAULT ((0)) NOT NULL,
    [IS_BONUS]                 INT             DEFAULT ((0)) NOT NULL,
    [DISCOUNT_TYPE]            VARCHAR (50)    NULL,
    [UNIT_MEASUREMENT]         VARCHAR (250)   NULL,
    [STATUS_CODE]              VARCHAR (50)    NULL,
    [BASE_REF]                 VARCHAR (50)    NULL,
    [BASE_ENTRY]               VARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([PICKING_DEMAND_DETAIL_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_MANIFEST_HEADER_PICKING_DEMAND_HEADER]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([LINE_NUM], [MATERIAL_ID], [QTY]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_HEADER_ID]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([ERP_OBJECT_TYPE], [LINE_NUM], [MASTER_ID_MATERIAL], [MATERIAL_ID], [MATERIAL_OWNER], [PICKING_DEMAND_DETAIL_ID], [PRICE], [QTY], [QTY_IMPLODED], [WAS_IMPLODED], [ERP_REFERENCE], [POSTED_RESPONSE]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_HEADER_ID_MATERIAL_ID_LINE_NUM]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC, [MATERIAL_ID] ASC, [LINE_NUM] ASC)
    INCLUDE([QTY]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_PICKING_DEMAND_HEADER_ID_INNER_SALE_STATUS]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC, [INNER_SALE_STATUS] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_NEXT_PICKING_DEMAND_DETAIL_PICKING_DEMAND_HEADER_ID_MATERIAL_OWNER]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC, [MATERIAL_OWNER] ASC)
    INCLUDE([INNER_SALE_RESPONSE], [INNER_SALE_STATUS], [PICKING_DEMAND_DETAIL_ID]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_IS_POSTED_ERP_PICKING_DEMAND_HEADER_ID]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([IS_POSTED_ERP] ASC, [PICKING_DEMAND_HEADER_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_MATERIAL_ID_PICKING_DEMAND_HEADER_ID_PICKING_DEMAND_HEADER_ID]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([MATERIAL_ID] ASC, [PICKING_DEMAND_HEADER_ID] ASC, [MASTER_ID_MATERIAL] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [ERP_OBJECT_TYPE], [ERP_REFERENCE], [IS_POSTED_ERP], [LINE_NUM], [POSTED_ERP], [POSTED_RESPONSE], [POSTED_STATUS], [PRICE], [QTY], [WAS_IMPLODED], [PICKING_DEMAND_DETAIL_ID]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_MATERIAL_ID_PICKING_DEMAND_HEADER_ID_PICKING_DEMAND_HEADER_ID_MATERIAL_OWNER]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([MATERIAL_ID] ASC, [PICKING_DEMAND_HEADER_ID] ASC, [MASTER_ID_MATERIAL] ASC, [MATERIAL_OWNER] ASC)
    INCLUDE([POSTED_ERP], [POSTED_RESPONSE], [POSTED_STATUS], [PRICE], [QTY], [WAS_IMPLODED], [ATTEMPTED_WITH_ERROR], [ERP_OBJECT_TYPE], [ERP_REFERENCE], [IS_POSTED_ERP], [LINE_NUM], [PICKING_DEMAND_DETAIL_ID]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_MATERIAL_OWNER_PICKING_DEMAND_HEADER_ID]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([MATERIAL_OWNER] ASC, [PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([ATTEMPTED_WITH_ERROR], [PICKING_DEMAND_DETAIL_ID], [POSTED_RESPONSE]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_PICKING_DEMAND_DETAIL_PICKING_DEMAND_DETAIL_ID]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_DETAIL_ID] ASC)
    INCLUDE([CALIBER], [TONE], [INNER_SALE_STATUS], [INNER_SALE_RESPONSE], [QTY_IMPLODED]);


GO
CREATE NONCLUSTERED INDEX [IDX_PICKING_DEMAND_DETAIL_IS_POSTED_ERP]
    ON [FERCO].[OP_WMS_NEXT_PICKING_DEMAND_DETAIL]([PICKING_DEMAND_HEADER_ID] ASC)
    INCLUDE([IS_POSTED_ERP], [POSTED_ERP], [POSTED_STATUS], [ATTEMPTED_WITH_ERROR]);

