CREATE TABLE [FERCO].[OP_WMS_SERVICE] (
    [SERVICE_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [SERVICE_CODE]        VARCHAR (25)  NULL,
    [SERVICE_DESCRIPTION] VARCHAR (250) NULL,
    [IS_EXTERNAL_SERVICE] INT           DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([SERVICE_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_SERVICE_SERVICE_CODE]
    ON [FERCO].[OP_WMS_SERVICE]([SERVICE_CODE] ASC);

