CREATE TABLE [FERCO].[OP_WMS_STATUS_OF_MATERIAL_BY_LICENSE] (
    [STATUS_ID]        INT           IDENTITY (1, 1) NOT NULL,
    [STATUS_NAME]      VARCHAR (100) NULL,
    [BLOCKS_INVENTORY] INT           NULL,
    [ALLOW_REALLOC]    INT           NULL,
    [TARGET_LOCATION]  VARCHAR (25)  NULL,
    [DESCRIPTION]      VARCHAR (200) NULL,
    [COLOR]            VARCHAR (20)  NULL,
    [STATUS_CODE]      VARCHAR (50)  NULL,
    [LICENSE_ID]       NUMERIC (18)  NULL,
    CONSTRAINT [PK_OP_WMS_STATUS_OF_MATERIAL_BY_LICENSE] PRIMARY KEY CLUSTERED ([STATUS_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_STATUS_OF_MATERIALS_BY_LICENSE_STATUS]
    ON [FERCO].[OP_WMS_STATUS_OF_MATERIAL_BY_LICENSE]([STATUS_ID] ASC, [STATUS_CODE] ASC)
    INCLUDE([BLOCKS_INVENTORY], [COLOR], [STATUS_NAME], [TARGET_LOCATION]);


GO
CREATE NONCLUSTERED INDEX [IDX_STATUS_OF_MATERIAL_BY_LICENSE_STATUS_ID_BLOCKS_INVENTORY]
    ON [FERCO].[OP_WMS_STATUS_OF_MATERIAL_BY_LICENSE]([STATUS_ID] ASC)
    INCLUDE([BLOCKS_INVENTORY]);


GO
CREATE NONCLUSTERED INDEX [IDX_BLOCKS_INVENTORY]
    ON [FERCO].[OP_WMS_STATUS_OF_MATERIAL_BY_LICENSE]([BLOCKS_INVENTORY] ASC)
    INCLUDE([STATUS_ID]);

