CREATE TABLE [FERCO].[OP_WMS_TRANS_23_03_2023] (
    [SERIAL_NUMBER]                              NUMERIC (18)     IDENTITY (1, 1) NOT NULL,
    [TERMS_OF_TRADE]                             VARCHAR (50)     NULL,
    [TRANS_DATE]                                 DATETIME         NOT NULL,
    [LOGIN_ID]                                   VARCHAR (25)     NOT NULL,
    [LOGIN_NAME]                                 VARCHAR (50)     NULL,
    [TRANS_TYPE]                                 VARCHAR (25)     NOT NULL,
    [TRANS_DESCRIPTION]                          VARCHAR (50)     NOT NULL,
    [TRANS_EXTRA_COMMENTS]                       VARCHAR (250)    NULL,
    [MATERIAL_BARCODE]                           VARCHAR (25)     NOT NULL,
    [MATERIAL_CODE]                              VARCHAR (50)     NOT NULL,
    [MATERIAL_DESCRIPTION]                       VARCHAR (200)    NULL,
    [MATERIAL_TYPE]                              VARCHAR (25)     NULL,
    [MATERIAL_COST]                              NUMERIC (18)     NULL,
    [SOURCE_LICENSE]                             NUMERIC (18)     NULL,
    [TARGET_LICENSE]                             NUMERIC (18)     NULL,
    [SOURCE_LOCATION]                            VARCHAR (25)     NULL,
    [TARGET_LOCATION]                            VARCHAR (25)     NOT NULL,
    [CLIENT_OWNER]                               VARCHAR (25)     NULL,
    [CLIENT_NAME]                                VARCHAR (150)    NULL,
    [QUANTITY_UNITS]                             NUMERIC (18, 4)  NOT NULL,
    [SOURCE_WAREHOUSE]                           VARCHAR (25)     NULL,
    [TARGET_WAREHOUSE]                           VARCHAR (25)     NULL,
    [TRANS_SUBTYPE]                              VARCHAR (25)     NULL,
    [CODIGO_POLIZA]                              VARCHAR (25)     NULL,
    [LICENSE_ID]                                 NUMERIC (18)     NULL,
    [STATUS]                                     VARCHAR (15)     NULL,
    [WAVE_PICKING_ID]                            NUMERIC (18)     NULL,
    [DAYS_IDLE]                                  NUMERIC (18)     NULL,
    [POSTED_TO_ERP_STAMP]                        DATETIME         NULL,
    [RELATED_SERVICES]                           VARCHAR (100)    NULL,
    [MESSAGE_FROM_ERP]                           VARCHAR (200)    NULL,
    [TRANS_WEIGTH]                               NUMERIC (18, 2)  NULL,
    [INVOICE_REFERENCE]                          VARCHAR (30)     NULL,
    [TRANS_MT2]                                  NUMERIC (18, 2)  NULL,
    [VIN]                                        VARCHAR (40)     NULL,
    [TASK_ID]                                    NUMERIC (18)     NULL,
    [IS_FROM_SONDA]                              INT              NULL,
    [SERIAL]                                     VARCHAR (50)     NULL,
    [BATCH]                                      VARCHAR (50)     NULL,
    [DATE_EXPIRATION]                            DATE             NULL,
    [CODE_SUPPLIER]                              VARCHAR (25)     NULL,
    [NAME_SUPPLIER]                              VARCHAR (100)    NULL,
    [SOURCE_TYPE]                                VARCHAR (50)     NULL,
    [TRANSFER_REQUEST_ID]                        INT              NULL,
    [TONE]                                       VARCHAR (20)     NULL,
    [CALIBER]                                    VARCHAR (20)     NULL,
    [ORIGINAL_LICENSE]                           INT              NULL,
    [ENTERED_MEASUREMENT_UNIT]                   VARCHAR (50)     NULL,
    [ENTERED_MEASUREMENT_UNIT_QTY]               NUMERIC (18, 4)  NULL,
    [ENTERED_MEASUREMENT_UNIT_CONVERSION_FACTOR] NUMERIC (18, 4)  NULL,
    [STATUS_CODE]                                VARCHAR (50)     NULL,
    [PROJECT_ID]                                 UNIQUEIDENTIFIER NULL,
    [PROJECT_CODE]                               VARCHAR (50)     NULL,
    [PROJECT_NAME]                               VARCHAR (150)    NULL,
    [PROJECT_SHORT_NAME]                         VARCHAR (25)     NULL
);

