CREATE TABLE [FERCO].[OP_WMS_MATERIAL_INTERCOMPANY] (
    [MASTER_ID] VARCHAR (50) NOT NULL,
    [ITEM_CODE] VARCHAR (50) NOT NULL,
    [SOURCE]    VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([MASTER_ID] ASC, [ITEM_CODE] ASC, [SOURCE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_INTERCOMPANY_SOURCE_ITEM_CODE]
    ON [FERCO].[OP_WMS_MATERIAL_INTERCOMPANY]([SOURCE] ASC, [ITEM_CODE] ASC)
    INCLUDE([MASTER_ID]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_MATERIAL_INTERCOMPANY_SOURCE_MASTER_ID]
    ON [FERCO].[OP_WMS_MATERIAL_INTERCOMPANY]([SOURCE] ASC, [MASTER_ID] ASC)
    INCLUDE([ITEM_CODE]);

