CREATE TABLE [FERCO].[OP_WMS_USER_X_PILOT] (
    [CODE]           INT          IDENTITY (1, 1) NOT NULL,
    [USER_CODE]      VARCHAR (25) NOT NULL,
    [PILOT_CODE]     INT          NOT NULL,
    [LAST_UPDATE]    DATETIME     DEFAULT (getdate()) NULL,
    [LAST_UPDATE_BY] VARCHAR (25) NULL,
    CONSTRAINT [PK_OP_WMS_USER_X_PILOT_CODE] PRIMARY KEY CLUSTERED ([CODE] ASC),
    FOREIGN KEY ([PILOT_CODE]) REFERENCES [FERCO].[OP_WMS_PILOT] ([PILOT_CODE]),
    FOREIGN KEY ([USER_CODE]) REFERENCES [FERCO].[OP_WMS_LOGINS] ([LOGIN_ID]),
    CONSTRAINT [U_OP_WMS_USER_X_PILOT_PILOT_CODE] UNIQUE NONCLUSTERED ([PILOT_CODE] ASC),
    CONSTRAINT [U_OP_WMS_USER_X_PILOT_USER_CODE] UNIQUE NONCLUSTERED ([USER_CODE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_USER_CODE_PILOT_CODE_USER_X_PILOT]
    ON [FERCO].[OP_WMS_USER_X_PILOT]([USER_CODE] ASC, [PILOT_CODE] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_USER_X_PILOT_CODE]
    ON [FERCO].[OP_WMS_USER_X_PILOT]([CODE] ASC)
    INCLUDE([LAST_UPDATE], [LAST_UPDATE_BY], [PILOT_CODE], [USER_CODE]);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_USER_X_PILOT_PILOT_CODE]
    ON [FERCO].[OP_WMS_USER_X_PILOT]([PILOT_CODE] ASC)
    INCLUDE([USER_CODE]);

