CREATE TABLE [FERCO].[OP_WMS_DELIVERED_DISPATCH_HEADER] (
    [DELIVERED_DISPATCH_HEADER_ID] INT          IDENTITY (1, 1) NOT NULL,
    [WAVE_PICKING_ID]              INT          NULL,
    [STATUS]                       VARCHAR (50) NULL,
    [CREATE_DATE]                  DATETIME     DEFAULT (getdate()) NULL,
    [CREATE_BY]                    VARCHAR (50) NULL,
    [LAST_UPDATE]                  DATETIME     NULL,
    [LAST_UPDATE_BY]               VARCHAR (50) NULL,
    [PICKING_DEMAND_HEADER_ID]     INT          NULL,
    PRIMARY KEY CLUSTERED ([DELIVERED_DISPATCH_HEADER_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_OP_WMS_DELIVERED_DISPATCH_HEADER_WAVE_PICKING_ID]
    ON [FERCO].[OP_WMS_DELIVERED_DISPATCH_HEADER]([WAVE_PICKING_ID] ASC)
    INCLUDE([STATUS]);

