CREATE TABLE [FERCO].[OP_WMS_SLOTTING_ZONE] (
    [ID]             UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [WAREHOUSE_CODE] VARCHAR (25)     NOT NULL,
    [ZONE_ID]        INT              NOT NULL,
    [ZONE]           VARCHAR (50)     NULL,
    [MANDATORY]      BIT              CONSTRAINT [DF_OP_WMS_SLOTTING_ZONE_MANDATORY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_WMS_SLOTTING_ZONE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_SLOTTING_ZONE_WAREHOUSE] FOREIGN KEY ([WAREHOUSE_CODE]) REFERENCES [FERCO].[OP_WMS_WAREHOUSES] ([WAREHOUSE_ID]),
    CONSTRAINT [FK_SLOTTING_ZONE_ZONE] FOREIGN KEY ([ZONE_ID]) REFERENCES [FERCO].[OP_WMS_ZONE] ([ZONE_ID])
);

