CREATE VIEW ferco.ERP_SKU_BASE_PRICE_BY_PACK 
AS SELECT *
	FROM OPENQUERY([SAPSERVER], '
		SELECT
			CAST(IT.PriceList AS VARCHAR) AS CODE_PRICE_LIST 
			,IT.ItemCode AS CODE_SKU
			,OU.UomCode AS CODE_PACK_UNIT
			,CAST(IT.Price AS NUMERIC(18,6)) AS COST
		FROM SBOFERCO.dbo.ITM9 IT
		INNER JOIN SBOFERCO.dbo.OUOM OU ON (
			OU.UomEntry = IT.UomEntry
		)
		ORDER BY IT.PriceList
			,IT.ItemCode
			,OU.UomCode
	')