

CREATE VIEW [ferco].[ERP_VIEW_PICKING]
AS
select SAP_PICKING_ID, ERP_DOC, CUSTOMER_ID, CUSTOMER_NAME, SKU, SKU_DESCRIPTION, QTY from openquery (SAPSERVER,'SELECT     CAST(POD.DocEntry AS VARCHAR) + CAST(POD.LineNum AS VARCHAR) AS SAP_PICKING_ID, POD.DocEntry AS ERP_DOC, PO.CardCode AS CUSTOMER_ID, PO.CardName AS CUSTOMER_NAME, 
                      POD.ItemCode AS SKU, POD.Dscription AS SKU_DESCRIPTION, POD.Quantity AS QTY
FROM         [SBOFERCO].dbo.RDR1 AS POD INNER JOIN
                      [SBOFERCO].dbo.ORDR AS PO ON PO.DocEntry = POD.DocEntry
WHERE     (PO.DocType = ''I'') ')