CREATE VIEW ferco.ERP_PRICE_LIST_BY_SKU_PACK_SCALE 
AS SELECT *
	FROM OPENQUERY(SAPSERVER, '
		SELECT 
			CAST(SP1.ListNum AS VARCHAR) AS CODE_PRICE_LIST 
			,SP1.ItemCode AS CODE_SKU
			,OU.UomCode AS CODE_PACK_UNIT
			,CAST(ISNULL(SP2.Amount,1) AS NUMERIC(18,0)) AS LIMIT
			,CAST(SP2.Price AS NUMERIC(18,6)) AS COST
		FROM SBOFERCO.dbo.SPP1 SP1
		INNER JOIN SBOFERCO.dbo.SPP2 SP2 ON (
			SP2.SPP1LNum = SP1.LINENUM 
			AND SP1.ItemCode = SP2.ItemCode 
			AND SP1.CardCode = SP2.CardCode
		)
		INNER JOIN SBOFERCO.dbo.OUOM OU ON (
			OU.UomEntry = SP2.UomEntry 
			AND SP1.ItemCode = SP2.ItemCode
		)
		INNER JOIN SBOFERCO.dbo.OITM OI ON (
			OI.ItemCode = SP1.ItemCode
		)
		WHERE OI.SellItem = ''Y''
		AND GETDATE() BETWEEN ISNULL(SP1.FromDate,DATEADD(DAY,-1,GETDATE())) AND ISNULL(SP1.ToDate,DATEADD(DAY,1,GETDATE()))
		ORDER BY SP1.ListNum
			,SP1.ItemCode
			,OU.UomCode
			,SP2.Amount
	')