CREATE TABLE [dbo].[OP_WMS_SLOTTING_ZONE] (
    [ID]             UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL,
    [WAREHOUSE_CODE] VARCHAR (25)     NOT NULL,
    [ZONE_ID]        INT              NOT NULL,
    [ZONE]           VARCHAR (50)     NULL,
    [MANDATORY]      BIT              CONSTRAINT [DF_OP_WMS_SLOTTING_ZONE_MANDATORY] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_OP_WMS_SLOTTING_ZONE] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (FILLFACTOR = 80, STATISTICS_NORECOMPUTE = ON)
);

